server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**

        - id: alumno-service
          uri: lb://alumno-service
          predicates:
            - Path=/alumnos/**
          filters:
            - AuthenticationFilter

        - id: cursos-service
          uri: lb://cursos-service
          predicates:
            - Path=/cursos/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/